mybatis-plus:
  mapper-locations: classpath*:com/zhengrz/meetingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

eureka:
  client:
    service-url:
      defaultZone: http://zhengrz:zhengrz_2020@localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:120.79.194.125}:${MYSQL_PORT:33061}/${DB_NAME:meeting_film}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:zhengrz@2020}
    filters: log4j,wall,mergeStat
  application:
    name: user-service

logging:
  config: classpath:logback.xml
server:
  port: 8201
